### PR TITLE
Autoinstall goimports

### PR DESCRIPTION
**Pull request by PXshadow**
Autoinstall at macro init time goimports if not already defined

### CODE REVIEW

**Review by neimanpinchas — APPROVED** [review]
Amazing this will streamline the path for newcomers, I sought this conveniance in your great hx2go project.

Phereps you want to remove the if (true|| on CompilerInit line 48.

Thank you

**Comment by PXshadow** [comment]
Yeah I do want to remove the line 48 part in CompilerInit good catch, sorry I meant to remove that, it was just for testing.

**Comment by neimanpinchas** [comment]
I think #4 of the roadmap is already done, except of the main creation part.

I think maybe it belongs anyway go into a seperate step.

**Comment by elliott5** [comment]
I think making a main.go file should be optional (though maybe the default), as the user may have an existing go system that (s)he wants to augment with existing haxe code.

Also, once a haxe system has been translated to go, it is likely that extra go code will be written to augment it, that extra code is likely to be referenced from main.go, if only to allow for correct initialisation.

**Pull request merged**
